Module-Identifiers DEFINITIONS AUTOMATIC TAGS ::=
BEGIN
IMPORTS
  Host, Port FROM Module-URI
Server-name ::= SEQUENCE { hostname Host,
                           port Port OPTIONAL }
Identifier ::= SEQUENCE { sigil Identifier-type, 
                          localpart Local-part, 
                          colon Colon DEFAULT ":",
                          domain Server-name } 

Local-part ::= IA5String( FROM ("a".."z" | "0".."9" | "._-="))

Identifier-type ::= ENUMERATED { user-id, room, event, room-alias }

Colon ::= IA5String (":")

END
